apiVersion: v1
kind: Service
metadata:
  name: video-worker-api
  namespace: ${apps_namespace}
spec:
  ports:
    - name: http
      port: 8083
      targetPort: http
  selector:
    app.kubernetes.io/name: video-worker-api
